FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt
COPY requirements-test.txt requirements-test.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements-test.txt

COPY . .

ENV PYTHONPATH=/app

CMD ["pytest", "--maxfail=1", "--disable-warnings", "-v"]
